imports:
    - { resource: services.yml }

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

framework:
    test: %kernel.debug%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
    secret: qwerty
    profiler:
        enabled: false
    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    use_controller: %kernel.debug%

apnet_assetic_importer:
    assets:
        compass_project2:
            source: %kernel.root_dir%/Resources/assets/compass_project2/config.rb
            target: scss_project2
            importer: compass
            watcher: true

# Apnet Assetic Watcher Bundle
apnet_assetic_watcher:
    compiler_root: %kernel.root_dir%/Resources
    enabled: true
