services:
    apnet.assetic.asset.dir1:
        class: Apnet\AsseticImporterBundle\Factory\AssetResource
        arguments:
            - %kernel.root_dir%/Resources/dir1
            - test1/dir2
        tags:
            - { name: apnet.assetic.resource }

    apnet.assetic.asset.style1_css:
        class: Apnet\AsseticImporterBundle\Factory\AssetResource
        arguments:
            - %kernel.root_dir%/Resources/style1.css
            - test2/style2.css
        tags:
            - { name: apnet.assetic.resource }
