services:
    apnet.assetic.asset.dir1:
        parent: assetic.importer_path
        arguments:
            - %kernel.root_dir%/Resources/assets/dir1
            - test1/dir2
        tags:
            - { name: apnet.assetic.asset_mapper }

    apnet.assetic.asset.style1_css:
        parent: assetic.importer_path
        arguments:
            - %kernel.root_dir%/Resources/assets/style1.css
            - test2/style2.css
        tags:
            - { name: apnet.assetic.asset_mapper }

    apnet.assetic.importer.compass_project1:
        parent: assetic.importer_compass
        arguments:
            - %kernel.root_dir%/../app/../app/Resources/../Resources/assets/compass_project1/config.rb
            - scss_project1
        tags:
            - { name: apnet.assetic.config_mapper, watcher: compass }

    apnet.assetic.importer.pre_project1:
        parent: assetic.importer_pre
        arguments:
            - %kernel.root_dir%/Resources/assets/pre_project1/config.yml
            - filters_project1
        tags:
            - { name: apnet.assetic.config_mapper, watcher: pre }

    # Twig extension
    apnet.dev.twig_extension:
        class: Apnet\Dev\TwigExtension
        tags:
            - { name: twig.extension }
