services:
    apnet.assetic.asset.dir1:
        parent: assetic.importer_path
        arguments:
            - %kernel.root_dir%/Resources/assets/dir1
            - test1/dir2
        tags:
            - { name: apnet.assetic.asset_mapper }

    apnet.assetic.asset.style1_css:
        parent: assetic.importer_path
        arguments:
            - %kernel.root_dir%/Resources/assets/style1.css
            - test2/style2.css
        tags:
            - { name: apnet.assetic.asset_mapper }

    apnet.assetic.importer.compass_project1:
        parent: assetic.importer_compass
        arguments:
            - %kernel.root_dir%/Resources/assets/compass_project1/config.rb
            - composer_project1
        tags:
            - { name: apnet.assetic.config_mapper, watcher: compass }
