parameters:
    apnet.assetic.importer_parser.compass.class: Apnet\AsseticImporterBundle\Parser\CompassConfig\Parser
    apnet.assetic.importer.compass.class: Apnet\AsseticImporterBundle\Factory\Importer\CompassImporter

services:
    # config.rb parser
    apnet.assetic.importer_parser.compass:
        class: %apnet.assetic.importer_parser.compass.class%

    # config.rb importer
    apnet.assetic.importer.compass:
        class: %apnet.assetic.importer.compass.class%
        arguments:
            - @apnet.assetic.importer_parser.compass

    # importer_compass service template
    assetic.importer_compass:
        class: %apnet.assetic.asset_mapper.class%
        factory: [ "@apnet.assetic.importer.compass", load ]
        public: false
        abstract: true
