parameters:
    apnet.assetic.importer_parser.compass.class: Apnet\AsseticImporterBundle\Parser\CompassConfigParser
    apnet.assetic.importer.compass.class: Apnet\AsseticImporterBundle\Factory\Importer\CompassImporter
    apnet.assetic.asset_watcher.compass.class: Apnet\AsseticImporterBundle\Factory\Watcher\CompassWatcher

services:
    # config.rb parser
    apnet.assetic.importer_parser.compass:
        class: %apnet.assetic.importer_parser.compass.class%

    # config.rb importer
    apnet.assetic.importer.compass:
        class: %apnet.assetic.importer.compass.class%
        arguments:
            - @apnet.assetic.importer_parser.compass

    # importer_compass service templae
    assetic.importer_compass:
        class: %apnet.assetic.asset_mapper.class%
        factory_service: apnet.assetic.importer.compass
        factory_method: load
        public: false
        abstract: true

    # config.rb watcher
    apnet.assetic.asset_watcher.compass:
        class: %apnet.assetic.asset_watcher.compass.class%
        arguments:
            - @apnet.assetic.importer_parser.compass
        tags:
            - { name: apnet.assetic.asset_watcher }
