parameters:
    apnet.assetic.importer_loader.class: Apnet\AsseticImporterBundle\Factory\Loader\CollectionLoader
    apnet.assetic.asset_manager_cache_warmer.class: Apnet\AsseticImporterBundle\CacheWarmer\AssetManagerCacheWarmer
    apnet.assetic.importer_resource.class: Apnet\AsseticImporterBundle\Factory\Resource\CollectionResource

services:
    apnet.assetic.importer_loader:
        class: %apnet.assetic.importer_loader.class%
        public: false
        tags:
            - { name: assetic.formula_loader, alias: apnet_importer_config }

    apnet.assetic.importer_resource:
        class: %apnet.assetic.importer_resource.class%
        tags:
            - { name: assetic.formula_resource, loader: apnet_importer_config }

    apnet.assetic.asset_manager_cache_warmer:
        class: %apnet.assetic.asset_manager_cache_warmer.class%
        public: false
        tags:
            - { name: kernel.cache_warmer, priority: 9 }
