parameters:
    apnet.assetic.importer_loader.class: Apnet\AsseticImporterBundle\Factory\Loader\CollectionLoader
    apnet.assetic.importer_resource.class: Apnet\AsseticImporterBundle\Factory\Resource\CollectionResource
    apnet.assetic.asset_mapper.class: Apnet\AsseticImporterBundle\Factory\AssetMapper
    apnet.assetic.importer_twig_extension.class: Apnet\AsseticImporterBundle\Twig\Extension\ImporterExtension
    apnet.assetic.asset_watcher.class: Apnet\AsseticImporterBundle\Factory\AssetWatcher

services:
    # Assetic loader
    apnet.assetic.importer_loader:
        class: %apnet.assetic.importer_loader.class%
        public: false
        tags:
            - { name: assetic.formula_loader, alias: apnet_importer_config }

    # Assetic resource
    apnet.assetic.importer_resource:
        class: %apnet.assetic.importer_resource.class%
        tags:
            - { name: assetic.formula_resource, loader: apnet_importer_config }

    # Twig extension
    apnet.assetic.importer_twig_extension:
        class: %apnet.assetic.importer_twig_extension.class%
        arguments:
            - @router
            - @apnet.assetic.importer_resource
        tags:
            - { name: twig.extension }

    # Asset watcher factory ?
    apnet.assetic.asset_watcher:
        class: %apnet.assetic.asset_watcher.class%
